### ISSUE TITLE
SerialPort.list is not a function

### ISSUE THREAD

**Issue by michaelmariaott** [ultimaterobotics/uECG_nodejs#1]
If I run "node server.js" after running "npm install express" and "npm install serialport"  get the following error:
```

waiting for new device...
/Applications/uECG_nodejs-main/server.js:62
	SerialPort.list().then( ports =>
	           ^

TypeError: SerialPort.list is not a function
    at wait_for_port (/Applications/uECG_nodejs-main/server.js:62:13)
    at init_serial (/Applications/uECG_nodejs-main/server.js:101:3)
    at Object.<anonymous> (/Applications/uECG_nodejs-main/server.js:109:1)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.6.0

```

I am on macOS.

**Comment by the-3d6** [comment]
Sorry, missed the notification.
That probably is due to changes in serialport 10.x library. According to their migration guide here https://serialport.io/docs/guide-upgrade , the following change is needed:
instead of
const SerialPort = require('serialport')
there should be
const { SerialPort } = require('serialport')
import { SerialPort } from 'serialport'

**Comment by astartav** [comment]
> If I run "node server.js" after running "npm install express" and "npm install serialport" get the following error:
> 
> ```
> 
> waiting for new device...
> /Applications/uECG_nodejs-main/server.js:62
> 	SerialPort.list().then( ports =>
> 	           ^
> 
> TypeError: SerialPort.list is not a function
>     at wait_for_port (/Applications/uECG_nodejs-main/server.js:62:13)
>     at init_serial (/Applications/uECG_nodejs-main/server.js:101:3)
>     at Object.<anonymous> (/Applications/uECG_nodejs-main/server.js:109:1)
>     at Module._compile (node:internal/modules/cjs/loader:1120:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
>     at Module.load (node:internal/modules/cjs/loader:998:32)
>     at Module._load (node:internal/modules/cjs/loader:839:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:17:47
> 
> Node.js v18.6.0
> ```
> 
> I am on macOS.

It's because the new major (10) version of serialport library has changed syntax and we haven't updated our code yet. 
We'll do that as soon as we have time, but for now, we have packaged some executables for Node 16.
Could you try a MacOS one and say if it works? 

https://github.com/ultimaterobotics/uECG_nodejs/raw/main/uecg_desktop_macos_v1_10.zip
